#!/bin/bash
# This script builds the Rusty Waglayla WASM32 SDK release.

# make the script fail for any failed command
set -e

rm -rf release/*
rm -rf web/*
rm -rf nodejs/*
rm -rf docs/*
rm -rf examples/nodejs/typescript/lib

mkdir -p release/waglayla-wasm32-sdk/web
mkdir -p release/waglayla-wasm32-sdk/nodejs
mkdir -p release/waglayla-wasm32-sdk/docs

# pushd .
# cd ../rpc/wrpc/wasm
# wasm-pack build --target web --out-name waglayla-rpc --out-dir web/waglayla-rpc --features wasm32-sdk $@
# popd

wasm-pack build --weak-refs --target web --out-name waglayla --out-dir web/waglayla-keygen --features wasm32-keygen $@
wasm-pack build --weak-refs --dev --target web --out-name waglayla --out-dir web/waglayla-keygen-dev --features wasm32-keygen $@

wasm-pack build --weak-refs --target web --out-name waglayla --out-dir web/waglayla-rpc --features wasm32-rpc $@
wasm-pack build --weak-refs --dev --target web --out-name waglayla --out-dir web/waglayla-rpc-dev --features wasm32-rpc $@

wasm-pack build --weak-refs --target web --out-name waglayla --out-dir web/waglayla-core --features wasm32-core $@
wasm-pack build --weak-refs --dev --target web --out-name waglayla --out-dir web/waglayla-core-dev --features wasm32-core $@

wasm-pack build --weak-refs --target web --out-name waglayla --out-dir web/waglayla --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target web --out-name waglayla --out-dir web/waglayla-dev --features wasm32-sdk $@

wasm-pack build --weak-refs --target nodejs --out-name waglayla --out-dir nodejs/waglayla --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target nodejs --out-name waglayla --out-dir nodejs/waglayla-dev --features wasm32-sdk $@

# wasm-pack build --target web --dev --out-name waglayla --out-dir build/docs/waglayla --features wasm32-sdk $@
typedoc --name "Waglayla WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/waglayla-keygen ./build/docs/waglayla-keygen.ts
typedoc --name "Waglayla WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/waglayla-rpc ./build/docs/waglayla-rpc.ts
typedoc --name "Waglayla WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/waglayla-core ./build/docs/waglayla-core.ts
typedoc --name "Waglayla WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/waglayla ./build/docs/waglayla.ts

# cp -r ../rpc/wrpc/wasm/web/waglayla-rpc release/waglayla-wasm32-sdk/web/waglayla-rpc
cp -r web/waglayla-keygen release/waglayla-wasm32-sdk/web/waglayla-keygen
cp -r web/waglayla-keygen-dev release/waglayla-wasm32-sdk/web/waglayla-keygen-dev

cp -r web/waglayla-rpc release/waglayla-wasm32-sdk/web/waglayla-rpc
cp -r web/waglayla-rpc-dev release/waglayla-wasm32-sdk/web/waglayla-rpc-dev

cp -r web/waglayla-core release/waglayla-wasm32-sdk/web/waglayla-core
cp -r web/waglayla-core-dev release/waglayla-wasm32-sdk/web/waglayla-core-dev

cp -r web/waglayla release/waglayla-wasm32-sdk/web/waglayla
cp -r web/waglayla-dev release/waglayla-wasm32-sdk/web/waglayla-dev

cp -r nodejs/waglayla release/waglayla-wasm32-sdk/nodejs/waglayla
cp -r nodejs/waglayla-dev release/waglayla-wasm32-sdk/nodejs/waglayla-dev

cp -r docs/waglayla-keygen release/waglayla-wasm32-sdk/docs/waglayla-keygen
cp -r docs/waglayla-rpc release/waglayla-wasm32-sdk/docs/waglayla-rpc
cp -r docs/waglayla-core release/waglayla-wasm32-sdk/docs/waglayla-core
cp -r docs/waglayla release/waglayla-wasm32-sdk/docs/waglayla

mkdir -p release/waglayla-wasm32-sdk/examples/data
cp -r examples/data/.gitignore release/waglayla-wasm32-sdk/examples/data/.gitignore
cp -r examples/nodejs release/waglayla-wasm32-sdk/examples/
cp -r examples/web release/waglayla-wasm32-sdk/examples/
cp -r examples/init.js release/waglayla-wasm32-sdk/examples/
cp -r examples/jsconfig.json release/waglayla-wasm32-sdk/examples/
cp -r examples/package.json release/waglayla-wasm32-sdk/examples/

pushd .
cd release/waglayla-wasm32-sdk/examples
npm install
popd

# tsc release/waglayla-wasm32-sdk/examples/nodejs/typescript/

cp index.html release/waglayla-wasm32-sdk/index.html
cp README.md release/waglayla-wasm32-sdk/README.md
cp CHANGELOG.md release/waglayla-wasm32-sdk/CHANGELOG.md
cp LICENSE release/waglayla-wasm32-sdk/LICENSE

node build/package-sizes.js
cp package-sizes.js release/waglayla-wasm32-sdk/package-sizes.js

pushd .
cd release
zip -q -r waglayla-wasm32-sdk.zip waglayla-wasm32-sdk
popd
