#!/bin/bash
set -e

./build-web $@

if [ "$1" == "--keygen" ]; then
    echo "building keygen"
    typedoc --name "Waglayla WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/waglayla-keygen ./build/docs/waglayla-keygen.ts
elif [ "$1" == "--rpc" ]; then
    echo "building rpc"
    typedoc --name "Waglayla WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/waglayla-rpc ./build/docs/waglayla-rpc.ts
elif [ "$1" == "--core" ]; then
    echo "building core"
    typedoc --name "Waglayla WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/waglayla-core ./build/docs/waglayla-core.ts
elif [ "$1" == "--sdk" ]; then
    echo "building full"
    typedoc --name "Waglayla WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/waglayla ./build/docs/waglayla.ts
else
    echo "building keygen"
    typedoc --name "Waglayla WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/waglayla-keygen ./build/docs/waglayla-keygen.ts
    echo "building rpc"
    typedoc --name "Waglayla WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/waglayla-rpc ./build/docs/waglayla-rpc.ts
    echo "building core"
    typedoc --name "Waglayla WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/waglayla-core ./build/docs/waglayla-core.ts
    echo "building full"
    typedoc --name "Waglayla WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/waglayla ./build/docs/waglayla.ts

fi